### PR TITLE
Fix benchmark measurement

### PR DESCRIPTION
**Pull request by nicoburns**
# Objective

Our current benchmarking setup is broken. It shares the same instance of taffy between every iteration the benchmark, meaning that all but the first iteration are trivially returning a single cached result for the entire tree.

## Change made

Switched from `b.iter()` to `b.iter_batched()` which allows for per-iteration setup. See https://bheisler.github.io/criterion.rs/book/user_guide/timing_loops.html

## Context

Our benchmarks did seem a bit too good to be true. And it turns out it was indeed an issue with the measurement setup.

## Feedback Wanted

Is there anything else that needs to be updated?

## New benchmark results

The new results (raw results below - I haven't yet compiled them into a table form) look a lot more realistic. We still seem to be a little faster than yoga, but we're now within the same order of magnitude. Also, the runtimes now seem to increase roughly linearly with node count (although there is some variation due to depth/width). The 10_000 node benchmarks we have been considering realistic are now running in 3-7ms

<details>
<summary>Initial raw benchmark results</summary>
<pre><code>
yoga benchmarks/10 nodes
                        time:   [1.9694 µs 1.9857 µs 2.0060 µs]
                        change: [+5593.7% +5668.0% +5754.9%] (p = 0.00 < 0.05)
                        Performance has regressed.
yoga benchmarks/100 nodes
                        time:   [40.254 µs 41.810 µs 42.860 µs]
                        change: [+11326% +11637% +11997%] (p = 0.00 < 0.05)
                        Performance has regressed.
yoga benchmarks/1_000 nodes
                        time:   [351.04 µs 357.48 µs 363.61 µs]
                        change: [+8777.6% +8905.2% +9045.1%] (p = 0.00 < 0.05)
                        Performance has regressed.
yoga benchmarks/10_000 nodes
                        time:   [3.6723 ms 3.7310 ms 3.8026 ms]
                        change: [+9977.7% +10142% +10305%] (p = 0.00 < 0.05)
                        Performance has regressed.
yoga benchmarks/100_000 nodes
                        time:   [39.358 ms 39.682 ms 40.487 ms]
                        change: [+2089.2% +2276.5% +2455.8%] (p = 0.00 < 0.05)
                        Performance has regressed.

big trees (wide)/10 nodes (2-level hierarchy)
                        time:   [3.9618 µs 4.0313 µs 4.1044 µs]
                        change: [+10331% +10621% +10897%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 3 outliers among 10 measurements (30.00%)
  2 (20.00%) low mild
  1 (10.00%) high mild
big trees (wide)/100 nodes (2-level hierarchy)
                        time:   [41.085 µs 41.723 µs 42.154 µs]
                        change: [+12654% +12901% +13106%] (p = 0.00 < 0.05)
                        Performance has regressed.
big trees (wide)/1_000 nodes (2-level hierarchy)
                        time:   [444.62 µs 456.66 µs 472.53 µs]
                        change: [+10289% +10726% +11377%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high severe
big trees (wide)/10_000 nodes (2-level hierarchy)
                        time:   [7.0896 ms 7.1415 ms 7.2664 ms]
                        change: [+16155% +16462% +16772%] (p = 0.00 < 0.05)
                        Performance has regressed.
big trees (wide)/100_000 nodes (2-level hierarchy)
                        time:   [235.71 ms 237.22 ms 238.69 ms]
                        change: [+2440.1% +3531.5% +5113.5%] (p = 0.00 < 0.05)
                        Performance has regressed.
Benchmarking big trees (wide)/100_000 nodes (7-level hierarchy): Collecting 10 samples in est
big trees (wide)/100_000 nodes (7-level hierarchy)
                        time:   [66.114 ms 67.102 ms 68.550 ms]
                        change: [+2118.2% +2725.2% +3423.1%] (p = 0.00 < 0.05)
                        Performance has regressed.

Benchmarking big trees (deep)/4000 nodes (12-level hierarchy): Collecting 10 samples in estim
big trees (deep)/4000 nodes (12-level hierarchy)
                        time:   [2.7516 ms 2.7634 ms 2.7899 ms]
                        change: [+17677% +17942% +18323%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high mild
Benchmarking big trees (deep)/10_000 nodes (14-level hierarchy): Collecting 10 samples in est
big trees (deep)/10_000 nodes (14-level hierarchy)
                        time:   [6.8138 ms 6.8414 ms 6.8971 ms]
                        change: [+16192% +16438% +16668%] (p = 0.00 < 0.05)
                        Performance has regressed.
Benchmarking big trees (deep)/100_000 nodes (17-level hierarchy): Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 6.5s or enable flat sampling.
Benchmarking big trees (deep)/100_000 nodes (17-level hierarchy): Collecting 10 samples in es
big trees (deep)/100_000 nodes (17-level hierarchy)
                        time:   [104.34 ms 104.85 ms 105.50 ms]
                        change: [+3270.1% +3842.8% +4400.8%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) low mild
Benchmarking big trees (deep)/1_000_000 nodes (20-level hierarchy): Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 9.2s.
Benchmarking big trees (deep)/1_000_000 nodes (20-level hierarchy): Collecting 10 samples in
big trees (deep)/1_000_000 nodes (20-level hierarchy)
                        time:   [801.84 ms 805.22 ms 808.36 ms]
                        change: [+186.55% +190.52% +194.51%] (p = 0.00 < 0.05)
                        Performance has regressed.

Benchmarking super deep trees/100 nodes (100-level hierarchy): Collecting 10 samples in estim
super deep trees/100 nodes (100-level hierarchy)
                        time:   [109.06 µs 109.86 µs 110.36 µs]
                        change: [+11171% +11223% +11282%] (p = 0.00 < 0.05)
                        Performance has regressed.
Benchmarking super deep trees/1_000 nodes (1000-level hierarchy): Collecting 10 samples in es
super deep trees/1_000 nodes (1000-level hierarchy)
                        time:   [1.1159 ms 1.1402 ms 1.1566 ms]
                        change: [+10026% +10188% +10370%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 2 outliers among 10 measurements (20.00%)
  2 (20.00%) high mild

     Running benches/complex.rs (target/release/deps/complex-dbe31e6a2fae0144)
Benchmarking deep hierarchy/build: Collecting 200 samples in estimated 5.0075 s (8.0M iterati
deep hierarchy/build    time:   [615.42 ns 616.90 ns 618.63 ns]
                        change: [-1.6804% -1.4685% -1.2538%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 5 outliers among 200 measurements (2.50%)
  3 (1.50%) high mild
  2 (1.00%) high severe
Benchmarking deep hierarchy/single: Collecting 200 samples in estimated 5.0400 s (1.1M iterat
deep hierarchy/single   time:   [4.6065 µs 4.6325 µs 4.6584 µs]
                        change: [+1.4065% +1.8424% +2.2578%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 36 outliers among 200 measurements (18.00%)
  15 (7.50%) high mild
  21 (10.50%) high severe
Benchmarking deep hierarchy/relayout: Collecting 200 samples in estimated 5.0078 s (2.3M iter
deep hierarchy/relayout time:   [2.1297 µs 2.1316 µs 2.1335 µs]
                        change: [+1.0168% +1.1888% +1.3784%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 5 outliers among 200 measurements (2.50%)
  4 (2.00%) high mild
  1 (0.50%) high severe

     Running benches/generated/mod.rs (target/release/deps/generated-22f12e16d7a12341)
Benchmarking generated benchmarks: Collecting 100 samples in estimated 5.6448 s (25k iteratio
generated benchmarks    time:   [225.74 µs 226.64 µs 227.52 µs]
                        change: [+1.5664% +1.9256% +2.2661%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 10 outliers among 100 measurements (10.00%)
  7 (7.00%) high mild
  3 (3.00%) high severe
 </code></pre>
 </details>
  
| Benchmark | Yoga | Taffy 0.1 | Taffy 0.2 | % change (0.1 -> 0.2) |
| --- | --- | --- | --- | --- |
| yoga/10 nodes (1-level hierarchy) | 45.1670 µs | 2.2851 µs | 2.0787 µs | -9.3338% |
| yoga/100 nodes (2-level hierarchy) | 134.1250 µs | 75.518 µs | 41.022 µs | -46.577% |
| yoga/1_000 nodes (3-level hierarchy) | 1.2221 ms | 1.7794 ms | 355.50 µs | -79.608% |
| yoga/10_000 nodes (4-level hierarchy) | 13.8672 ms | 52.117 ms | 3.6848 ms | -92.968% |
| yoga/100_000 nodes (5-level hierarchy) | 141.5307 ms | 1.5626 s | 39.830 ms | -97.459% |
| yoga /1_000_000 nodes (6-level hierarchy) | -  | - | 384.19 ms | - |
| wide/10 nodes (2-level hierarchy) | - | 6.1508 µs | 4.1094 µs | -33.923% |
| wide/100 nodes (2-level hierarchy) | - | 66.602 µs | 41.056 µs | -35.742% |
| wide/1_000 nodes (2-level hierarchy) | - | 699.18 µs | 445.01 µs | -36.279% |
| wide/10_000 nodes (2-level hierarchy) | - | 8.8244 ms | 7.1313 ms | -16.352% |
| wide/100_000 nodes (2-level hierarchy) | - | 204.48 ms | 242.93 ms | +18.803% |
| semi-wide/100_000 nodes (7-level hierarchy) | - | 2.6539 s | 69.141 ms | -97.402% |
| deep/4000 nodes (12-level hierarchy)) | - | 5.2320 s | 2.7363 ms | -99.947% |
| deep/10_000 nodes (14-level hierarchy) | - | 75.207 s | 6.9415 ms | -99.991% |
| deep/100_000 nodes (17-level hierarchy) | - | - | 102.72 ms| - |
| deep/1_000_000 nodes (20-level hierarchy) | - | - | 799.35 ms | - |
| super-deep/100 nodes (100-level hierarchy) | - | - | 111.26 µs | - |
| super-deep/1000 nodes (1000-level hierarchy) | - | - | 1.1746 ms | - |
| deep hierarchy/build  | - | 1.5060 µs | 616.12 ns | -1.5167% |
| deep hierarchy/single | - | 7.1453 µs | 4.5461 µs | -0.5156% |
| deep hierarchy/relayout | - | 3.7863 µs | 2.1275 µs | -1.0900% |
| generated benchmarks  | - | 255.83 µs | 221.73 µs | -13.125% |

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Can you update the README in this PR too?

**Comment by nicoburns** [comment]
README and markdown benchmarks updated (also now included in the PR description). I backported the fix to the 0.1.x branch so we can get accurate 0.1 -> 0.2 changes.

**Comment by TimJentzsch** [comment]
Ah dang, that's on me.
I think I didn't understand how taffy cached the results when I wrote the initial benchmarks so I thought building a new tree would be sufficient.

Does that mean that the taffy 0.1 benchmarks were also wrong? Or did it cancel out because the old caching didn't work properly?

**Comment by nicoburns** [comment]
> I think I didn't understand how taffy cached the results when I wrote the initial benchmarks so I thought building a new tree would be sufficient.

You are actually correct that building a new tree is sufficient (the cache is stored on the node, so if you build a new tree then this implies an empty cache). I think what you didn't understand was that old code was not in fact building a new tree for each iteration of the benchmark. `b.iter()` runs and measures it's closure multiple times in order to calculate an average run time reduce measurement error due to variability in run times, but the setup code in the closure passed to the outer `group.bench_function` only runs once. The fix here is use `b.iter_batched()` which accepts a second closure for setup which does get run for each iteration.

> Does that mean that the taffy 0.1 benchmarks were also wrong? Or did it cancel out because the old caching didn't work properly?

The taffy 0.1 benchmarks were also wrong. I think the percentage comparisons between 0.1 and 0.2 were actually not affected that much in most cases because the error would *mostly* cancel itself out, but the absolute results and the comparisons to Yoga were way off (we seem to be around 4x faster than yoga rather than 1000x).

I've updated the benchmarks for Taffy 0.1 in this PR too. You can compare the old and new results by comparing the deleted markdown file with the added one.

**Comment by TimJentzsch** [comment]
Ahh right, I see it now. I built the tree outside the `.iter` closure.
Probably to not measure the build time as well, but that broke it even more.

Too bad that we already advertised taffy with the false numbers, but at least we can fix it now.
Maybe we should do a second post on Bevy Discord/Reddit to correct this mistake.

**Pull request merged**
