### PR TITLE
Rename PositionType and Position in accordance to specs

### LINKED ISSUE #271: Name of `position` and `position_type` properties doesn't match CSS spec
### Problem

- What we call `position_type` is Taffy is `position`  in the CSS spec https://developer.mozilla.org/en-US/docs/Web/CSS/position
- What we call `position` is `inset` in the CSS spec. https://developer.mozilla.org/en-US/docs/Web/CSS/inset

### Context

I suspect `inset` hadn't yet been specified when Taffy/Stretch was first created.

### Proposal

Rename `position` to `inset` and `position_type` to `position` to align with the CSS names for these properties.

### PR DESCRIPTION
**Pull request by Weibye**
# Objective

Fix #271

### CODE REVIEW

**Comment by nicoburns** [comment]
This looks good to me, but CSS Grid tests are failing. You need to run tests with `--features experimental_grid`. And if you want Rust-Analyzer to pick up the grid modules you have to temporarily makes `experimental_grid` a default feature in `Cargo.toml`.

@alice-i-cecile This is becoming an increasingly annoying problem for me when working on Taffy. How would you feel about making the grid feature on by default? (and perhaps renaming it to just `grid` or `css-grid`?)

**Comment by alice-i-cecile** [comment]
I'm fine to enable them by default now!

**Review by alice-i-cecile — APPROVED** [review]
Happy to merge this once CI is passing.

**Comment by Weibye** [comment]
All should be fixed now :)

**Pull request merged**
