### PR TITLE
Fix 1px wide gaps between adjacent UI nodes

### LINKED ISSUE #369: 1 Pixel gap between adjacent nodes
## `taffy` version
0.3.2
## Platform

What platform are you using `taffy` on? Rust
## What you did
```rust
use taffy::prelude::*;

fn main() {
    // First create an instance of Taffy
    let mut taffy = Taffy::new();

    let w = 100.3;

    let w_square = Size {
        width: points(w),
        height: points(w),
    };
    let child_a = taffy
        .new_leaf(Style {
            size: w_square,
            ..Default::default()
        })
        .unwrap();

    let child_b = taffy
        .new_leaf(Style {
            size: w_square,
            ..Default::default()
        })
        .unwrap();

    let root_node = taffy
        .new_with_children(
            Style {
                size: Size {
                    width: points(963.3333),
                    height: points(1000.),
                },
                justify_content: Some(JustifyContent::Center),
                ..Default::default()
            },
            &[child_a, child_b],
        )
        .unwrap();

    taffy.compute_layout(root_node, Size::MAX_CONTENT).unwrap();

    let layout_a = taffy.layout(child_a).unwrap();
    let layout_b = taffy.layout(child_b).unwrap();
    assert_eq!(
        layout_a.location.x + layout_a.size.width,
        layout_b.location.x
    );
}

```
## What went wrong

- what were you expecting?
No gap between adjacent nodes
- what actually happened?
1 Pixel gap
## Additional information

- theories about what might be going wrong
This probably has to do with rounding, see [comment in bevy issue](https://github.com/bevyengine/bevy/issues/7712#issuecomment-1436098176)
- links to related bugs, PRs or discussions
Bug report on Bevy bevyengine/bevy#7712

### PR DESCRIPTION
**Pull request by nicoburns**
# Objective

Fixes #369

## Context

- https://github.com/DioxusLabs/taffy/issues/369
- https://github.com/bevyengine/bevy/issues/7712
- https://github.com/facebook/yoga/commit/aa5b296ac78f7a22e1aeaf4891243c6bb76488e2
- https://github.com/DioxusLabs/taffy/pull/145

## Changes Made

- Add `enabled_rounding` and `disable_rounding` method to `Taffy` struct to allow consumers of Taffy to obtain unrounded values if they want them.
- Revert rounding changes from https://github.com/DioxusLabs/taffy/pull/145
- Add test for "no 1px gaps" from #369
- Update gentest runner to use new rounding mode. We're basically just running the same rounding algorithm in JavaScript using float values obtained from Chrome using `getBoundingClientRect`. This is also what Yoga does.
- Special case two tests to run in unrounded mode because they're failing with the new rounding. I have manually verified that this is just due to Taffy's lower precision (only using f32) making it round the other way as that test happens to have values *very* close to exactly `0.5` of a pixel (which isn't too important I don't think).
- Enable two previous disabled tests that came from Yoga (names starting with `rounding_controversy`).

## Feedback wanted

- High-level sense check: does this seems like the correct fix?
- On testing: As we're effectively running the rounding algorithm ourselves in the test generator, it's questionable how value we're actually getting from testing the rounding. The alternative would be to run tests on the float values. We won't get exact equality here, but we could run with something like "difference is < 0.1" which is what I've done for the two failing tests mentioned above. That would allow us to test a little more precisely than we currently are. On the other hand, we have tests that are specifically there to test rounding, for which it would seem silly to omit rouding. Perhaps we should just leave as-is for now and consider converting tests to use floats in future?

### CODE REVIEW

**Comment by nicoburns** [comment]
@mockersf @ickshonpe @A-Walrus would be good to get your reviews on this if possible.

**Comment by ickshonpe** [comment]
Looks good in Bevy. No gaps appear in any of the previous example cases.
The update broke text wrapping again somewhere, but it's probably something I introduced while hacking everything together etc.

**Comment by A-Walrus** [comment]
Looks good to me! Seems like a simple and sensible approach to round the right/left/top/bottom instead of the width.
In terms of testing IDK if it's better to compare rounded or unrounded. Would be nice if it was possible to get the values from Chrome's rounding, but I understand it's not exposed...

**Comment by nicoburns** [comment]
> Would be nice if it was possible to get the values from Chrome's rounding, but I understand it's not exposed...

Yeah, I think the only way to do this would be to take screenshots and then measure the resultant images. Which is feasable seeing as we're using headless chrome anyway. But it would work completely differently to our existing test harness.

**Review by alice-i-cecile — APPROVED** [review]
Sensible fix, great context, good tests. I think that the screenshot tests are worth considering in the future, but only if we have several reasons to want it.

Lots of complexity there.

**Pull request merged**
