### PR TITLE
incorrect padding and border calculation 

### PR DESCRIPTION
**Pull request by ickshonpe**
## Context

Fixes this: 

```rust
use taffy::prelude::*;

fn main() {
    let mut taffy = Taffy::new();

    let node = taffy.new_leaf(Style {
        padding: Rect { left: points(10.), right: points(0.), top: points(0.), bottom: points(0.)  },
        ..Default::default()
    }).unwrap();
    
    taffy.compute_layout(
        node, 
        Size { height: AvailableSpace::Definite(100.0), width: AvailableSpace::Definite(100.0) }
    )
    .ok();

    println!("{:#?}", node, taffy.layout(node).unwrap());
}
```

output:

```
node DefaultKey(1v1): Layout {
    order: 0,
    size: Size {
        width: 10.0,
        height: 10.0, 
    },
    location: Point {
        x: 0.0,
        y: 0.0,
    },
}
```

height should be 0.

The horizontal_axis_sum() of the padding and border is being incorrectly added to the node's height in `taffy::compute::leaf::Compute`

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Thanks! Can you add a note about this to the release notes?

**Comment by TimJentzsch** [comment]
Can you add a test for this?
I'm surprised that this wasn't caught by the other tests

**Comment by ickshonpe** [comment]
I'll do it

**Comment by nicoburns** [comment]
Doh, that's a stupid bug (introduced by me I hasten to add - I'm not calling anyone else stupid). We'll definitely want a test for this.

@alice-i-cecile I think this will require a 0.2.2 release. It was a bit of a pain arranging this last time due to branch protection. Would it be possible to update the branch protection for the `0.2.x` so it is protected against force pushes, but does allow maintainers to push regular commits without a PR? That way our workflow for releases could be to land all changes on `main` and then cherry-pick them back to `0.2.x`.

**Comment by ickshonpe** [comment]
Yep, the only reason I'm okay at finding bugs is because my own code is such a mess I know where to look hehe.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
> @alice-i-cecile I think this will require a 0.2.2 release. It was a bit of a pain arranging this last time due to branch protection. Would it be possible to update the branch protection for the 0.2.x so it is protected against force pushes, but does allow maintainers to push regular commits without a PR? That way our workflow for releases could be to land all changes on main and then cherry-pick them back to 0.2.x.

@nicoburns Agreed! I've allowed folks with write permissions to add commits directly to 0.* branches, but still block force pushes.  Ping me if that's not working for you.

**Pull request merged**
