### PR TITLE
Prepare for 0.3.13 release

### PR DESCRIPTION
**Pull request by nicoburns**
# Objective

Prepare for 0.3.13 release

## Context

Backports the following PRs from the `main` branch:

- https://github.com/DioxusLabs/taffy/pull/517
- https://github.com/DioxusLabs/taffy/pull/522
- https://github.com/DioxusLabs/taffy/pull/521
- https://github.com/DioxusLabs/taffy/pull/497
- https://github.com/DioxusLabs/taffy/pull/491
- https://github.com/DioxusLabs/taffy/pull/481
- https://github.com/DioxusLabs/taffy/pull/473

## Feedback wanted

Does it seem reasonable to release https://github.com/DioxusLabs/taffy/pull/497 in a patch release? It could technically break (change) people's layouts if they currently have `border` or `padding` set on a leaf node. However, it would be quite odd if anybody did have this set as it would currently be having no effect. Nevertheless, we could release this in a minor version update instead.

### CODE REVIEW

**Review by TimJentzsch — APPROVED** [review]
Personally I think that breaking changes in patch releases are fine if they fix errors, as they are not breaking the _intended_ behavior.

I also agree that it's highly unlikely that anyone is relying on this behavior.

**Comment by alice-i-cecile** [comment]
> # Objective
> Prepare for 0.3.13 release
> 
> ## Context
> Backports the following PRs from the `main` branch:
> 
> * [Fixed clippy lint errors (needless_pass_by_ref_mut) #517](https://github.com/DioxusLabs/taffy/pull/517)
> * [Flexbox: pass correct cross-axis available space when computing an item's intrinsic main size (+misc fixes) #522](https://github.com/DioxusLabs/taffy/pull/522)
> * [Fix rounding accumulation bug #521](https://github.com/DioxusLabs/taffy/pull/521)
> * [Reserve space for padding/borders/scrollbars in nodes with measure functions #497](https://github.com/DioxusLabs/taffy/pull/497)
> 
> This release should also include:
> 
> * [Fix: Make CSS Grid algorithm correctly apply max width/height and available space when it is the root node #491](https://github.com/DioxusLabs/taffy/pull/491)
> 
> So we will need to wait for that to land on main (and then cherry-picked into this PR) before merging and releasing.
> 
> ## Feedback wanted
> Does it seem reasonable to release #497 in a patch release? It could technically break (change) people's layouts if they currently have `border` or `padding` set on a leaf node. However, it would be quite odd if anybody did have this set as it would currently be having no effect. Nevertheless, we could release this in a minor version update instead.

This is my opinion as well.

**Comment by alice-i-cecile** [comment]
The final linked PR is merged now: just needs backporting right?

**Comment by nicoburns** [comment]
Right, let's include #497 then. If there's pushback from users then plan is:

- Release `0.3.14` with #497 reverted
- Create a `0.4.0` that is `0.3.14` with #497 reinstated
- Make current main `0.5.0` when it's released

I've backported that last PR, and also found a couple more PRs to include. FWIW, most of these had small conflicts that needed to be resolved (and/or applied cleanly but then caused test failures), so hopefully we won't need to do too many backports to the 0.3.x branch!

**Comment by nicoburns** [comment]
Converting back to a draft as Squash Merge is the only option, and I don't think this one ought to be squashed.

**Pull request merged**
