### PR TITLE
Added unreachable macro to alleged unreachable code rather than using hidden default value

### LINKED ISSUE #168: Mark unreachable code in `perform_absolute_layout_on_absolute_children` as such
## What problem does this solve or what need does it fill?

Using default values for code that _should_ not be reachable is dangerous, we should instead ensure that the code is actually not reached. If it turns out that it can (and should) be reached, we have to make sure that the behavior is correct.

## What solution would you like?

Use the `unreachable!()` macro in the following line:
<https://github.com/DioxusLabs/taffy/blob/e75a55f57946eeffb1a436925c88213c1102e57f/src/flexbox.rs#L1515>

If it turns out that this code _can_ be reached, make sure that the value is correct and remove the comment.

## What alternative(s) have you considered?

Leave it as-is. However, this could be the source of hard-to-detect errors.

## Additional context

N/A

### PR DESCRIPTION
**Pull request by Sheepyhead**
# Objective

Fixes  #168

## Context

This doesn't seem to panic any tests, but this still confers a risk to users that this code has actually been reached by some edge cases, where it would simply fail silently before.

## Feedback wanted

- If you have code depending on taffy, I'd really like to know if you get a panic from this PR, the more real dirty user code we test this on the better

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by mockersf** [comment]
> * If you have code depending on taffy, I'd really like to know if you get a panic from this PR, the more real dirty user code we test this on the better

No need to worry, it's impossible to fall in that case... as long as `align_self()` doesn't change
https://github.com/DioxusLabs/taffy/blob/e75a55f57946eeffb1a436925c88213c1102e57f/src/style.rs#L475-L487

It could be interesting to add a comment on that method to say it should never return `AlignSelf::Auto`

**Comment by TimJentzsch** [comment]
> This doesn't seem to panic any tests, but this still confers a risk to users that this code has actually been reached by some edge cases, where it would simply fail silently before.

IMO this is good, it's usually better to fail early and detect these kind of bugs instead of failing silently and causing problems in other areas that are hard to track back.

**Review by TimJentzsch — APPROVED** [review]

**Comment by Sheepyhead** [comment]
> IMO this is good, it's usually better to fail early and detect these kind of bugs instead of failing silently and causing problems in other areas that are hard to track back.

I agree, still it's something to note about this innocent-looking two-line PR ;)

**Comment by Sheepyhead** [comment]
> > Should I add that as part of this PR?
> 
> Yes please!

Idk if the way I did it works, but it was the best I could think of

**Comment by Weibye** [comment]
@Sheepyhead Please run `cargo fmt` on the code then push the changes :) Everything else is good to go 🚀

**Review by alice-i-cecile — APPROVED** [review]

**Pull request merged**
