### PR TITLE
Remove manual map implementation in `MaybeMath`

### PR DESCRIPTION
**Pull request by TimJentzsch**
# Objective

The implementations of `MaybeMath` used `#[allow(clippy::manual_map)]`.
This PR removes this lint suppression and applies `cargo clippy --fix` to use `map` instead of the `match` statement.

## Context

The original implementation justified the lint suppression as follows:

> The logic here is subtle and critical;
> explicit match statements make it more clear what's going on

## Feedback wanted

Do the explicit map statements really make it more clear what's going on?
Personally, I think the `map` statements are also clear.
If we're unsure if something works we should add unit tests instead.
I think it's good to suppress as little lints as possible.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
I'm fine with this as long as we solve #158 at the same time :)

**Review by Weibye — COMMENTED** [review]
I'm fine with the changes as long as we add both some docs and tests that together explain exactly what they do. I've just started learning about `.map` these last days so my reading comprehension is not yet at a level where I look at the implementation and intuitively know what's up.

**Comment by TimJentzsch** [comment]
> I'm fine with the changes as long as we add both some docs and tests that together explain exactly what they do. I've just started learning about `.map` these last days so my reading comprehension is not yet at a level where I look at the implementation and intuitively know what's up.

Hmm it's definitely a fair point that `.map` is harder to understand for users new to Rust / functional programming, however I'm not sure if adding documentation from `std` functions to our code base is a good idea

**Comment by TimJentzsch** [comment]
Looks like the tests are passing, now we still need to figure out if this is easier or harder to read/understand

**Comment by alice-i-cecile** [comment]
Given that this does the obvious thing + we have unit tests and docs now, I'm going to merge this.

I don't love keeping clippy allows around either.

**Pull request merged**
